
export let  data0: Object[] = [
       { x: 'Food', y: 90 },
       { x: 'Transport', y: 80 },
       { x: 'Medical', y: 50 },
       { x: 'Clothes', y: 70 },
       { x: 'Personal Care', y: 30 },
       { x: 'Books', y: 10 },
       { x: 'Fitness', y: 100 },
       { x: 'Electricity', y: 55 },
       { x: 'Tax', y: 20 },
       { x: 'Pet Care', y: 40 },
       { x: 'Education', y: 45 },
       { x: 'Entertainment', y: 75 },
   ];
   export let  data1: Object[] = [
       { x: 'Food', y: 40 },
       { x: 'Transport', y: 90 },
       { x: 'Medical', y: 80 },
       { x: 'Clothes', y: 30 },
       { x: 'Personal Care', y: 80 },
       { x: 'Books', y: 40 },
       { x: 'Fitness', y: 30 },
       { x: 'Electricity', y: 95 },
       { x: 'Tax', y: 50 },
       { x: 'Pet Care', y: 20 },
       { x: 'Education', y: 15 },
       { x: 'Entertainment', y: 45 },
   ];
   export let  data2: Object[] = [
       { x: 'Food', y: 70 },
       { x: 'Transport', y: 110 },
       { x: 'Medical', y: 120 },
       { x: 'Clothes', y: 60 },
       { x: 'Personal Care', y: 80 },
       { x: 'Books', y: 30 },
       { x: 'Fitness', y: 70 },
       { x: 'Electricity', y: 55 },
       { x: 'Tax', y: 40 },
       { x: 'Pet Care', y: 80 },
       { x: 'Education', y: 45 },
       { x: 'Entertainment', y: 65 },
   ];
   export let data3: Object[] = [
       { x: 'Food', y: 120 },
       { x: 'Transport', y: 70 },
       { x: 'Medical', y: 50 },
       { x: 'Clothes', y: 180 },
       { x: 'Personal Care', y: 30 },
       { x: 'Books', y: 270 },
       { x: 'Fitness', y: 40 },
       { x: 'Electricity', y: 75 },
       { x: 'Tax', y: 65 },
       { x: 'Pet Care', y: 95 },
       { x: 'Education', y: 135 },
       { x: 'Entertainment', y: 115 },
   ];
   
