export let sampleData: Object[] = [

  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 30,
    "FeatureName": "User Master",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": false,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": true,
    "Delete": false,
    "Export": false,
    "IsHeader": false,
    "FeatureCode": 0,
    subtasks:[
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 8,
        "FeatureName": "Zone Details",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": true,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 21,
    "FeatureName": "Roles",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": true,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": false,
    "Delete": false,
    "Export": false,
    "IsHeader": true,
    "FeatureCode": 0
  },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 31,
        "FeatureName": "User List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": true,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0

      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3129,
        "FeatureName": "User Activity",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      }

    ]
  },
  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 27,
    "FeatureName": "Station Details\r\n Master",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": false,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": false,
    "Delete": false,
    "Export": false,
    "IsHeader": false,
    "FeatureCode": 0,
    subtasks: [
      { "RoleId": 5,
        "Code": null,
        "FeatureId": 28,
        "FeatureName": "Station List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": true,
        "Edit": false,
        "Active": false,
        "Delete": true,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 42,
        "FeatureName": "Manage Station",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": true,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 10,
        "FeatureName": "Copy Multiple Channel",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": true,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 49,
        "FeatureName": "Query Setting",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": true,
        "Active": false,
        "Delete": false,
        "Export": true,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 11,
        "FeatureName": "Custom Equation",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      }
    ]
  },
  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 27,
    "FeatureName": "Settings",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": false,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": false,
    "Delete": false,
    "Export": false,
    "IsHeader": false,
    "FeatureCode": 0,
    subtasks: [
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 39,
        "FeatureName": "Port Setting",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": true,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 2072,
        "FeatureName": "Alarm Tag Setting",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 5,
        "FeatureName": "Analog Channel List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 13,
        "FeatureName": "Digital Channel List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3102,
        "FeatureName": "Login Page Setting",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      }
    ]

  },
  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 3111,
    "FeatureName": "Depolarisation",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": false,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": false,
    "Delete": false,
    "Export": false,
    "IsHeader": false,
    "FeatureCode": 0,
    subtasks : [
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3120,
        "FeatureName": "Set Depol",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": true,
        "Add": false,
        "Edit": false,
        "Active": true,
        "Delete": false,
        "Export": true,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3121,
        "FeatureName": "Create Depol Group",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": true,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3122,
        "FeatureName": "Tag Settings  for Depol",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": true,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3123,
        "FeatureName": "Register Settings for Depol",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": true,
        "Edit": false,
        "Active": false,
        "Delete": true,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      }
    ]
  },
  {
    "RoleId": 5,
    "Code": null,
    "FeatureId": 3111,
    "FeatureName": "templates",
    "ProgrammerCode": null,
    "Controller": null,
    "Action": null,
    "Url": null,
    "ParentId": 0,
    "SortIndex": 0,
    "IsDisplayForRoleRights": false,
    "View": false,
    "Add": false,
    "Edit": false,
    "Active": false,
    "Delete": false,
    "Export": false,
    "IsHeader": false,
    "FeatureCode": 0,
    subtasks:[
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 62,
        "FeatureName": "Mimic Template Master",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3097,
        "FeatureName": "Create Mimic Template",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0

      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 61,
        "FeatureName": "Mimic Template List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 2085,
        "FeatureName": "TRU Location",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },
      {
        "RoleId": 5,
        "Code": null,
        "FeatureId": 20,
        "FeatureName": "Report Template Master",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },{
        "RoleId": 5,
        "Code": null,
        "FeatureId": 15,
        "FeatureName": "Email Template Master",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },{
        "RoleId": 5,
        "Code": null,
        "FeatureId": 17,
        "FeatureName": "Create Email Template",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },{
        "RoleId": 5,
        "Code": null,
        "FeatureId": 16,
        "FeatureName": "Email Template List",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      },{
        "RoleId": 5,
        "Code": null,
        "FeatureId": 3108,
        "FeatureName": "GIS Template Master",
        "ProgrammerCode": null,
        "Controller": null,
        "Action": null,
        "Url": null,
        "ParentId": 0,
        "SortIndex": 0,
        "IsDisplayForRoleRights": false,
        "View": false,
        "Add": false,
        "Edit": false,
        "Active": false,
        "Delete": false,
        "Export": false,
        "IsHeader": false,
        "FeatureCode": 0
      }
    ]

  }


];
